/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class mac_MacOSDarkMode */

#ifndef _Included_MacOSDarkMode
#define _Included_MacOSDarkMode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mac_MacOSDarkMode
 * Method:    isDarkModeEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_MacOSDarkMode_isDarkModeEnabled
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
