/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class me_catcoder_themeswitcher_plugin_mac_MacOSDarkMode */

#ifndef _Included_me_catcoder_themeswitcher_plugin_mac_MacOSDarkMode
#define _Included_me_catcoder_themeswitcher_plugin_mac_MacOSDarkMode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_catcoder_themeswitcher_plugin_mac_MacOSDarkMode
 * Method:    isDarkModeEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_me_catcoder_themeswitcher_plugin_mac_MacOSDarkMode_isDarkModeEnabled
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
